### PR TITLE
Use go modules cache

### PR DESCRIPTION
**Pull request by hanzei**
This should speed up the build a bit.

Taken from https://circleci.com/blog/go-v1.11-modules-and-circleci/ and https://github.com/mattermost/mattermost-cloud/blob/master/.circleci/config.yml#L7-L15

### CODE REVIEW

**Review by crspeller — APPROVED** [review]

**Review by cpanato — APPROVED** [review]

**Comment by cpanato** [comment]
@crspeller who will release this? you? or me? :)

**Comment by hanzei** [comment]
>  who will release this? you? or me? :)

@cpanato Should I create a ticket for this?

**Comment by cpanato** [comment]
dont need

**Comment by cpanato** [comment]
published: mattermost/plugin-ci@0.0.5

**Pull request merged**
